# Zoho Data Store Configuration
zoho.enabled=true
zoho.project.id=26566000000013009
zoho.env.id=60061261997
zoho.region=accounts.zoho.in
zoho.users.table.id=users
zoho.client.id=1000.VJZHI5O3V1D0FTX43ZF5GO5DYVH6WL
zoho.client.secret=fe94ab88f6add088abd1df93d032d37d23b8b7767e
# New Refresh Token with Scopes: projects.READ, tables.READ, tables.rows.*, zcql.CREATE
zoho.refresh.token=1000.a733d5fd3ba92493173670ffb0bd3f88.ef338f70345193ad890263b6602f9528
# zoho.pat.token is removed as it does not work for Data Store REST API

# Exclude JPA/Datasource Auto-configuration (Safety net)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
